generatorName: spring
inputSpec: openapi.yaml
outputDir: generated/
additionalProperties:
  interfaceOnly: true
  skipDefaultInterface: true
  useTags: true
  apiPackage: com.gabrieldears.talent_forge.api
  modelPackage: com.gabrieldears.talent_forge.model
validationAnnotationPlacement: field

server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:talent_forge}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource.hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 30000
    connection-timeout: 20000
    max-lifetime: 1800000
management:
  endpoints:
    web:
      exposure:
        include: health,info


