generatorName: spring
inputSpec: openapi.yaml
outputDir: generated/
additionalProperties:
  interfaceOnly: true
  skipDefaultInterface: true
  useTags: true
  apiPackage: com.gabrieldears.talent_forge.api
  modelPackage: com.gabrieldears.talent_forge.model
validationAnnotationPlacement: field

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: candidate-matcher-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:talent_forge}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource.hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 30000
    connection-timeout: 20000
    max-lifetime: 1800000

management:
  tracing:
    propagation:
      type: w3c
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://tempo:4317
      protocol: grpc
      export:
        enabled: true

  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    io.micrometer.tracing: DEBUG
    io.opentelemetry: DEBUG
    io.opentelemetry.exporter.otlp: DEBUG
    io.micrometer.tracing.exporter: DEBUG
    org.springframework.boot.actuate.autoconfigure.tracing: DEBUG



ai:
  matcher:
    url: ${AI_MATCHER_URL:http://localhost:8000}
